<style>
.btn_main{
    width:90px;
    height: 90px;
    border-radius: 20px;
    font-size: 3em;
    opacity: 1 !imporant;
}
.content_button{
    text-align: center;
    padding:10px;
}

.textbox{
    width:80px;
    height: 80px;
    text-align:center;
    font-size:2em
}

</style>
<script>
    function putnumber(numero){
        elnumero=$(numero).attr("number");
        if($("#num1").val()=="")
            $("#num1").val(elnumero)
        else{
            if($("#num2").val()=="")
                $("#num2").val(elnumero)
            else{
                if($("#num3").val()=="")
                    $("#num3").val(elnumero)
                else{
                    if($("#num4").val()==""){
                        $("#num4").val(elnumero)
                        $("#form_acceso").submit();
                    }
                }
            }
        }
        
    }

    function eraser(){
        $("#num1").val("");
        $("#num2").val("");
        $("#num3").val("");
        $("#num4").val("");
    }
</script>
<center>
<div style="width: 600px;background-color: white; opacity: .8; padding:5px">
                <?if (isset($this->msgError)): echo $this->msgError; endif;?>
                    <img style="width:100px;"src="<?php echo $this->path?>/images/logo.png">                
                <hr/>    
                            
                <form action="<?php echo $this->path?>/Mandas" id="form_acceso" method="POST">
                <table>
                    <tr>
                        <td style="padding:15px;"><input class="textbox" id="num1" name="num1" type="password"  readonly/></td>
                        <td style="padding:15px;"><input class="textbox" id="num2" name="num2" type="password"  readonly/></td>
                        <td style="padding:15px;"><input class="textbox" id="num3" name="num3" type="password"  readonly/></td>
                        <td style="padding:15px;"><input class="textbox" id="num4" name="num4" type="password"  readonly/></td>                        
                    </tr>
                </table>  
                <table>
                    <tr>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="1" >1</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="2" >2</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="3" >3</button></td>
                    </tr>
                    <tr>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="4" >4</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="5" >5</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="6" >6</button></td>
                    </tr>
                    <tr>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="7" >7</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="8" >8</button></td>
                        <td  class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="9" >9</button></td>
                    </tr>                
                    <tr>
                        <td  colspan="1" ></td>                        
                        <td  colspan="1" class="content_button"><button type="button" class="btn btn-primary btn_main" onclick="putnumber(this)" number="0" >0</button></td>                        
                        <td  colspan="1" class="content_button"><button type="button" class="btn btn-secondary btn_main" onclick="eraser()" ><i class="fa fa-eraser"></i></button></td>                        
                    </tr>                
                </table>   
                
                </form>                           
</div>
</center>
<script>
    setTimeout(function(){$("#errorlogin").hide('slow')},2000);
</script>

