<style>
.manda{
    width: 80%;
    height: 100px;
    font-size: 12pt;
    
}

.redondo{
        -moz-border-radius-bottomleft: 10px;
        -webkit-border-bottom-left-radius: 10px;
        -moz-border-radius-bottomright: 10px;
        -webkit-border-bottom-right-radius: 10px;
        -moz-border-radius-topright: 10px;
        -webkit-border-top-right-radius: 10px;
        -moz-border-radius-topleft: 10px;
        -webkit-border-top-left-radius: 10px;        
        border-bottom-right-radius: 10px;
        border-bottom-left-radius: 10px;
        border-top-left-radius: 10px;        
        border-top-right-radius: 10px; 
        border-color:#b4b4b4;
    }


</style>

<center>
<div style="width:95%;background-color:white;color:black;overflow:scroll;">
<table style="width:100%">
    <tr>
        <td style="text-align:left">
            <div style="width:100%;text-align: left;padding-top:20px; padding-left:20px;"><a style="color:white" href="<?php echo $this->path?>/Mandas"><button class="btn btn-dark" style="width:80px;height:80px;"><span style="font-size:30pt;"><i class="fa fa-arrow-left"></i></span></button></a></div>
        </td>
        <td style="text-align:center;">
        <h1><?php echo date("d - m - Y")?></h1>
        <h3>Panel: <?php echo $this->mesero?></h3>        
        </td>
        <td style="text-align:right">
        <div style="width:100%;text-align: right;padding-top:20px; padding-right:20px;"><a style="color:white" href="<?php echo $this->path?>/Mandas/nueva"><button class="btn btn-dark" style="width:80px;height:80px;"><span style="font-size:30pt;"><i class="fa fa-plus"></i></span></button></a></div>
        </td>
    </tr>  
</table>
<hr/>
    
<div style="height:500px;overflow:scroll;">
 <?php $contador = 1; if($this->mandas!=null):?>
    <table style="width:95%;text-align:center;">
    <tr>
    <?php foreach($this->mandas as $manda): ?>
    <?php if($contador==5): $contador=1;?>
        </tr><tr>
    <?php endif;
        switch($manda->estado){
            case "iniciada": 
            case "actualizada":                    
                $fondo = "btn-info";    
                break;
            case "cancelada":
                $fondo = "btn-light";
            break;
            case "cerrada":
                $fondo = "btn-success";
            break;
        }
    
    ?>
        <td style="padding:20px;"><form action="<?php echo $this->path?>/Mandas/editar" method="POST" > <input type="hidden" name="mandas_id" value="<?php echo $manda->id?>"> <button type="submit" class="btn <?php echo $fondo?> manda redondo">Pedido <?php echo $manda->id?><br/> Mesa: <?php echo $manda->mesa?><br/>Monto: <?php echo "$ ".number_format($manda->total,2)?> <br/><?php echo date("d-m-Y",strtotime($manda->fecha_registro))?></button> </form> </td>
    <?php $contador++; endforeach;?>
    </tr>        
    </table>    
<?php  else:?>
<div style="width:100%" class="alert alert-info">No existen Mandas registradas</div>
 <?php endif;?>  
 </div>
</div>
</center>