<?php if(isset($this->resultado)):?>

<?php if($this->resultado):?>
<script>
    setTimeout(function(){$("#modal-bodyProveedor").html('<div id="result_item" class="alert alert-success" style=""><i class="fa fa-check"></i> Proveedor almacenado Satisfactoriamente!</div>')},200);
</script>
<?php else:?>
<script>
    setTimeout(function(){$("#modal-bodyProveedor").html('<div id="result_item" class="alert alert-warning" style=""><i class="fa fa-close"></i> Ocurrió un error, intente más tarde!</div>')},200);
</script>
<?php endif;?>
<script>
    // setTimeout(function(){$("#result_item").show("slow")},200)
    // setTimeout(function(){$("#result_item").hide("slow")},2000)
    setTimeout(function(){$("#infoProveedor").modal("show")},300)
</script>
<?php endif;?>
<div id="layoutAuthentication" style="">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-12">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header" style="background-color:white;color:black;"><h3 class="text-center font-weight-light my-4">Registrar Proveedor</h3></div>
                                <div class="card-body">
                                    <form action="<?php echo $this->path?>/Proveedores/index" method="POST" enctype="multipart/form-data">
                                        <div style="text-align:center">                                                                                        
                                        </div> 
                                        <h2 style="color:gray">Fiscales</h2>                                                                        
                                        <div class="form-row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputNombre">Persona:</label>
                                                    <select class="form-control custom-select custom-select-lg mb-3" id="selectPersona" name="tipo_persona">
                                                        <option value="fisica">Física</option>
                                                        <option value="moral">Moral</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputRFC">RFC*</label>
                                                    <input class="form-control py-4" id="inputRFC" name="rfc" maxlength="13" type="text" placeholder="RFC" required/>
                                                </div>
                                            </div>                                            
                                        </div>                                                                                       
                                        <h2 style="color:gray">Generales</h2>                                                                        
                                        <div class="form-row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputNombre">Nombre o Razón social*</label>
                                                    <input class="form-control py-4" id="inputNombre" name="nombre" maxlength="50" type="text" placeholder="Nombre del Proveedor" required/>
                                                </div>
                                            </div>                                            
                                        </div>                                                                                             
                                        <h2 style="color:gray">Domicilio Fiscal</h2>                                      
                                        <div class="form-row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputCalle">Calle*</label>
                                                    <input class="form-control py-4" id="inputCalle" name="calle" type="text" placeholder="calle" required/>
                                                </div>
                                            </div>
                                            <div class="col-md-1">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputNumInterno"># Int.</label>
                                                    <input class="form-control py-4" id="inpuNumInterno" name="num_interno" type="text" placeholder="No. I" />
                                                </div>
                                            </div>
                                            <div class="col-md-1">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputNumExterno"># Ext.*</label>
                                                    <input class="form-control py-4" id="inputNumExterno" name="num_externo" type="text" placeholder="No. E" />
                                                </div>
                                            </div>                                           
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputColonia">Colonia</label>
                                                    <input class="form-control py-4" id="inputColonia" name="colonia" type="tex" placeholder="Colonia" />
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputLocalidad">Localidad</label>
                                                    <input class="form-control py-4" id="inputLocalidad" name="localidad" type="text" placeholder="Localidad" />
                                                </div>
                                            </div>
                                        </div>      
                                        <div class="form-row">
                                        <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputMunicipio">Municipio</label>
                                                    <input class="form-control py-4" id="inputMunicipio" name="municipio" type="tex" placeholder="Municipio" />
                                                </div>
                                            </div>
                                        <div class="col-md-2">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputCp">C.P.</label>
                                                    <input class="form-control py-4" id="inputCp" name="cp" type="text" placeholder="C.P." />
                                                </div>
                                        </div>                                                                                                                                                                        
                                        <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputEstado">Estado</label>
                                                    <input class="form-control py-4" id="inputEstado" name="estado" type="text" placeholder="Estado" />
                                                </div>
                                            </div>                                              
                                        </div> 
                                        <h2 style="color:gray">Contacto</h2>
                                        <div class="form-row">
                                        <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputTelefonoCasa">Teléfono de casa</label>
                                                    <input class="form-control py-4" id="inputTelefonoCasa" name="telefono_casa" type="text" placeholder="Teléfono" />
                                                </div>
                                        </div>
                                        <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputCelular">Celular</label>
                                                    <input class="form-control py-4" id="inputCelular" name="telefono_celular" type="text" placeholder="Celular" />
                                                </div>
                                        </div>
                                        <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputCorreo">Correo electrónico</label>
                                                    <input class="form-control py-4" id="inputCorreo" name="correo_electronico" type="text" placeholder="Correo electrónico" />
                                                </div>
                                        </div>
                                        </div>
                                        <!-- <h2 style="color:gray">Laboral</h2>
                                        <div class="form-row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="selectArea">Área de empleo*</label>
                                                    <select class="form-control custom-select custom-select-lg mb-3" id="selectArea" name="area_trabajo">
                                                        <option value="mesero">Mesero</option>
                                                        <option value="cocina">Cocina</option>
                                                        <option value="barra">Barra</option>
                                                        <option value="administrador">Administrador</option>
                                                    </select>
                                                </div>                                               
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="selectTurno">Turno*</label>
                                                    <select class="form-control custom-select custom-select-lg mb-3" id="selectTurno" name="turno">
                                                        <option value="matutino">Matutino</option>
                                                        <option value="vespertino">Vespertino</option>
                                                        <option value="mixto">Mixto</option>                                                        
                                                    </select>
                                                </div>                                               
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputCodigo">Clave Acceso*</label>
                                                    <input class="form-control py-4" id="inputCodigo" name="codigo_acceso" type="text" placeholder="Clave Acceso" required/>
                                                </div>
                                        </div>
                                        </div> -->                                            
                                        <div class="form-group mt-4 mb-0" style="text-align:right"><a href="<?php echo $this->path?>/Proveedores/listado"><button  type="button" class="btn btn-secondary">Cancelar</button></a>&nbsp;&nbsp;&nbsp;<button class="btn btn-primary">Almacenar Proveedor</button></div>
                                    </form>
                                </div>
                                <div class="card-footer text-center">
                                    <div class="small"><a href="login.html"></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>            
    </div>
    <script>
        setTimeout(function(){$("#collapseProveedores").addClass("show");},1)
    </script>
<div class="modal fade" id="infoProveedor" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header" style="background-color:white;color:black;">
                <h5 class="modal-title" id="exampleModalLongTitle" >Resultado de Almacenamiento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-bodyProveedor">                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                
            </div>
            </div>
        </div>
        </div>