<style>
    .sombreado {
        background-color: #F9F7F7;
    }
</style>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Catálogo de Artículos
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="dataTableItems" width="100%" cellspacing="0" lang="es">
                <thead>
                    <tr style="background-color:black;color:white;">
                        <th>Id</th>
                        <!--<th>Identificador</th>-->
                        <th>Artículo</th>
                        <th>Tipo</th>
                        <th>Unidad de Medida</th>
                        <?php if ($this->varSession->rol == "ADMINISTRADOR") : ?>
                            <th>Costo</th>
                        <?php endif; ?>
                        <th>Precio Menudeo</th>
                        <th>Precio Mayoreo</th>
                        <th>Precio Distribuidor</th>
                        <th>Existencias</th>
                        <th style="display:none">Avatar</th>
                        <?php if ($this->varSession->rol == "ADMINISTRADOR") : ?>
                            <th>Acciones</th>
                        <?php endif; ?>

                    </tr>
                </thead>
                <!--<tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Position</th>
                                                <th>Office</th>
                                                <th>Age</th>
                                                <th>Start date</th>
                                                <th>Salary</th>
                                            </tr>
                                        </tfoot>-->
                <tbody>
                    <?php $bandera = true;
                    if ($this->productos != null) : ?>
                        <?php foreach ($this->productos as $producto) : ?>
                            <tr class="<?php echo $bandera ? "sombreado" : ""; ?>">
                                <td><?php echo $producto->id ?></td>
                                <!--<td><?php echo $producto->identificador ?></td>-->
                                <td><?php echo $producto->nombre ?></td>
                                <td><?php echo $producto->categoria ?></td>
                                <td><?php echo $producto->unidad_medida ?></td>
                                <?php if ($this->varSession->rol == "ADMINISTRADOR") : ?>
                                    <td style="text-align:right"><?php echo "$ " . number_format($producto->costo, 2) ?></td>
                                <?php endif; ?>
                                <td style="text-align:right"><?php echo "$ " . number_format($producto->precio_publico, 2) ?></td>
                                <td style="text-align:right"><?php echo "$ " . number_format($producto->precio_mayoreo, 2) ?></td>
                                <td style="text-align:right"><?php echo "$ " . number_format($producto->precio_distribuidor, 2) ?></td>
                                <td style="text-align:right"><?php echo $producto->existencias ?></td>
                                <?php if ($producto->avatar != "") : ?>
                                    <td style="text-align:center;display:none"><img style="width:50px;" src="<?php echo $this->path . "/images/items/" . $producto->avatar ?>"></td>
                                <?php else : ?>
                                    <td style="text-align:center;display:none"><img style="width:50px;" src="<?php echo $this->path . "/images/items/generic.png" ?>"></td>
                                <?php endif ?>
                                <?php if ($this->varSession->rol == "ADMINISTRADOR") : ?>
                                    <td style="text-align:center">
                                        <form style="display:inline;" action="<?php echo $this->path ?>/Productos/editar" method="POST"><input type="hidden" name="items_id" value="<?php echo $producto->id ?>"><button type="submit" class="btn btn-info"><i class="fa fa-edit"></i></button></form>
                                        <form style="display:inline;" action="<?php echo $this->path ?>/Productos/eliminar" method="POST"><input type="hidden" name="items_id" value="<?php echo $producto->id ?>"><button type="submit" class="btn btn-warning"><i class="fa fa-trash "></i></button></form>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php $bandera = !$bandera;
                        endforeach; ?>
                    <?php endif; ?>


                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    setTimeout(function() {
        $("#collapseLayouts").addClass("show");
    }, 1)
</script>
<script>
    setTimeout(function() {
        $('#dataTableItems thead tr')
            .clone(true)
            .addClass('filters')
            .appendTo('#dataTableItems thead');

        dt = $('#dataTableItems').DataTable({
            pageLength: 10,
            lengthMenu: [10, 30, 50],
            orderCellsTop: true,
            fixedHeader: true,
            initComplete: function() {
                var api = this.api();

                // For each column
                api
                    .columns()
                    .eq(0)
                    .each(function(colIdx) {
                        // Set the header cell to contain the input element
                        var cell = $('.filters th').eq(
                            $(api.column(colIdx).header()).index()
                        );
                        var title = $(cell).text();
                        if (colIdx != 10) {
                            $(cell).html(
                                '<input type="text" class="form-control" placeholder="' +
                                title + '" />');
                        } else {
                            $(cell).html('')
                        }


                        // On every keypress in this input
                        $(
                                'input',
                                $('.filters th').eq($(api.column(colIdx).header()).index())
                            )
                            .off('keyup change')
                            .on('change', function(e) {
                                // Get the search value
                                $(this).attr('title', $(this).val());
                                var regexr =
                                    '({search})'; //$(this).parents('th').find('select').val();

                                var cursorPosition = this.selectionStart;
                                // Search the column for that value
                                api
                                    .column(colIdx)
                                    .search(
                                        this.value != '' ?
                                        regexr.replace('{search}', '(((' + this.value +
                                            ')))') :
                                        '',
                                        this.value != '',
                                        this.value == ''
                                    )
                                    .draw();
                            })
                            .on('keyup', function(e) {
                                e.stopPropagation();

                                $(this).trigger('change');
                                $(this)
                                    .focus()[0]
                                    .setSelectionRange(cursorPosition, cursorPosition);
                            });
                    });
            },
        });

    }, 500);
</script>