<?php if(isset($this->resultado)):?>
<?php if($this->resultado):?>
<script>
    setTimeout(function(){$("#modal-bodyItem").html('<div id="mensaje" style="" class="alert alert-success"><i class="fa fa-check-circle"></i> El artículo ha sido dado de baja Satisfactoriamente!</div>')},200);
</script>
<?php else:?>
<script>
    setTimeout(function(){$("#modal-bodyItem").html('<div id="mensaje" style="" class="alert alert-warning">Ocurrió un error al Dar de baja el Artículo, favor de intentar más tarde!</div>')},200);
</script>
<?php endif;?>
<script>
// setTimeout(function(){$("#mensaje").show("");},200);
// setTimeout(function(){$("#mensaje").hide("slow");},2000);
setTimeout(function(){$("#infoItem").modal("show")},300)
setTimeout(function(){window.location.replace("<?php echo $this->path?>/Productos/catalogo");},2500);

</script>
<?php endif;?>

<?php if($this->infoItem!=null):?>
    <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-12">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header" style="background-color:black;color:white"><h3 class="text-center font-weight-light my-4">¿Confirma Eliminar este Producto?</h3></div>
                                    <div class="card-body">
                                        <form action="<?php echo $this->path?>/Productos/eliminar" method="POST" enctype="multipart/form-data">
                                        <input type="hidden" name="items_id" value="<?php echo $this->infoItem->id?>">
                                            <div style="text-align:center">
                                                <span id="avatar">
                                                    <!--<i style='font-size:5em' class='fa fa-spinner fa-spin fa-3x fa-fw'></i>-->
                                                    <img  style="width:200px" src="<?php echo $this->path?>/images/items/<?php echo $this->infoItem->avatar==""?"generic.png":$this->infoItem->avatar?>"/>
                                                </span>
                                                
                                            </div>                                            
                                            <br/>                                                                                                                                                                                                         
                                            <div class="form-row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputNombre">Nombre del Producto*</label>
                                                        <input class="form-control py-4" disabled id="inputNombre" name="nombre" maxlength="30" type="text" placeholder="Nombre del Producto" required value="<?php echo $this->infoItem->nombre?>"/>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputAlias">Alias*</label>
                                                        <input class="form-control py-4" disabled id="inputAlias" name="alias" maxlength="15" type="text" placeholder="Alias" required value="<?php echo $this->infoItem->alias?>"/>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <div class="form-row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="inputPrecio">Precio*</label>
                                                        <input class="form-control py-4" disabled id="inputPrecio" name="precio" type="money" placeholder="$ 0.00" required value="<?php echo $this->infoItem->precio_publico?>"/>
                                                    </div>
                                                </div>
                                                <?php switch($this->infoItem->categorias_id):
                                                    
                                                    case 1:
                                                        $cat = "Bebida";
                                                        break;
                                                    case 2:
                                                        $cat = "Alimento";
                                                        break;
                                                    case 3:
                                                        $cat = "Otro";
                                                        break;
                                                    ?>

                                                <?php endswitch;?>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="small mb-1" for="selectCategoria">Categoria*</label>
                                                        <input class="form-control py-4" disabled value="<?php echo $cat?>"/>
                                                    </div>
                                                </div>
                                            </div>                                                                                                                                    
                                            <div class="form-group mt-4 mb-0" style="text-align:center"><a href="<?php echo $this->path?>/Productos/catalogo"><button  type="button" class="btn btn-primary">No</button></a>&nbsp;&nbsp;&nbsp;<button type="submit" name="confirmasi" class="btn btn-warning" value="si">Si</button></div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="login.html"></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>            
        </div>
<?php endif;?>
<div class="modal fade" id="infoItem" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header" style="background-color:black;color:white;">
                <h5 class="modal-title" id="exampleModalLongTitle" >Resultado de Baja de Producto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-bodyItem">                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                
            </div>
            </div>
        </div>
        </div>