<?php if($this->turno!=null):?>
<div id="layoutAuthentication" style="">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header" style="background-color:green;color:white;"><h3>Entradas de Efectivo</h3><h3 class="text-center font-weight-light my-4">Turno Activo: <span id="turnos_id"><?php echo $this->turno;?></span></h3></div>
                                <div class="card-body">                                    
                                        <div style="text-align:center">                                                                                        
                                        </div> 
                                        <h2 style="color:gray">Saldo Final</h2>                                                                        
                                        <div class="form-row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                   <center><h1> <div style="text-align:center"> <span id="saldo_final"><?php echo number_format($this->infoTurno->saldo_final,2)?></span></div></h1></center>
                                                </div>
                                            </div>                                            
                                        </div>    
                                        <div class="form-row">
                                        <div class="col-md-5">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputMonto">Cantidad a Ingresar:</label>
                                                    <input class="form-control py-4" style="font-size:2em;" id="inputMonto" name="monto" maxlength="13" type="text" placeholder=" 0.00" required/>
                                                </div>                                                
                                        </div>                                        
                                        </div>
                                        <div class="form-row">
                                        <div class="col-md-8">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="inputMotivo">Comentarios:</label>
                                                    <input class="form-control py-4" style="font-size:2em;" id="inputMotivo" name="motivo"  type="text" required/>
                                                </div>                                                
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group" style="">
                                                <br/>
                                                <button  style="height:61px;" type="button" class="btn btn-success" id="button_entrada" onclick="addEntrada()">Ingresar Efectivo</button>                                                    
                                            </div>
                                        </div>
                                        </div>
                                        <div class="form-row">
                                            <table class="table">
                                                <thead style="background-color:#33B5FF;color:black;">
                                                    <tr>
                                                        <th>id</th>
                                                        <th>Fecha</th>
                                                        <th>Entrada</th>
                                                        <th>Comentarios</th>
                                                        <th></th>
                                                    </tr>                                                
                                                </thead>
                                                <tbody id="rowsentradas">   
                                                 <?php if($this->entradas):?>
                                                    <?php foreach($this->entradas as $entrada):?>
                                                        <tr id="entrada<?php echo $entrada->id?>">
                                                            <td><?php echo $entrada->id?></td>
                                                            <td><?php echo date("Y-m-d",strtotime($entrada->fecha))?></td>
                                                            <td>$ <?php echo number_format($entrada->monto,2)?></td>
                                                            <td> <?php echo $entrada->motivo?></td>                                                            
                                                            <td>
                                                                <a target="_blank" href="<?php echo $this->path?>/Caja/imprimeentrada?entrada=<?php echo $entrada->id?>"><button class="btn btn-success"><i class="fas fa-print"></i></button></a>
                                                                <button class="btn btn-warning" id="buttonentrada<?php echo $entrada->id?>"onclick="cancelaEntrada(<?php echo $entrada->id?>,<?php echo $entrada->monto?>)"><i class="fa fa-times"></i></button>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                 <?php endif;?>   


                                                </tbody>
                                            </table>
                                        </div>
                                        </div>                                                                                                                                                                                                       
                                        <!-- <div class="form-group mt-4 mb-0" style="text-align:right"><a href="<?php echo $this->path?>/Clientes/listado"><button  type="button" class="btn btn-secondary">Cancelar</button></a>&nbsp;&nbsp;&nbsp;<button class="btn btn-primary">Almacenar Cliente</button></div>                                     -->
                                </div>
                                <div class="card-footer text-center">
                                    <div class="small"><a href="login.html"></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>            
    </div>    
<?php endif;?>
<div class="modal fade" id="infoEntrada" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header" style="background-color:gray;color:white;">
                <h5 class="modal-title" id="exampleModalLongTitle" >Mensaje de Retiro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-bodyRetiro">                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                
            </div>
            </div>
        </div>
        </div>



<script>
        setTimeout(function(){$("#collapseCaja").addClass("show");},1)
</script>