<div class="card-body">
                                <div class="table-responsive" >
                                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0" lang="es">
                                        <thead>
                                            <tr style="background-color:blue;color:white;">
                                                <th>Id</th>
                                                <th>Fecha</th>                                                
                                                <th>Proveedor</th>
                                                <th>Tipo Documento</th>
                                                <th>Identificador</th>
                                                <th>Total de la Compra</th>
                                                <th>Usuario</th>                                                
                                                <th>Acciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if($this->compras!=null):?>              
                                        <?php foreach($this->compras as $compra):?>
                                            <tr id="rowcompra<?php echo $compra->id?>">
                                                <td><?php echo $compra->id ?></td>
                                                <td><?php echo $compra->fecha_compra ?></td>
                                                <td><?php echo $compra->proveedor ?></td>
                                                <td><?php echo $compra->tipo_documento ?></td>
                                                <td><?php echo $compra->identificador ?></td>
                                                <td style="text-align:center"><?php echo "$ ".number_format($compra->total_compra,2) ?></td>
                                                <td><?php echo $compra->empleado ?></td>
                                                <td style="text-align:center">
                                                    <button class="btn btn-info" onclick="$('#infoCompra').modal('show'); getDetalleCompra(<?php echo $compra->id?>)" style="width:40px;"><i class="fa fa-info" style="color:white;"></i></button>                                                    
                                                    <button class="btn btn-warning" onclick="$('#delCompra').modal('show'); inicializaEliminarCompra(); $('#compraId').html('<?php echo $compra->id?>');" style="width:40px;"><i class="fa fa-trash" style="color:white;"></i></button>
                                                </td>
                                            </tr>
                                        <?php endforeach;?>
                                        <?php endif;?>
                                        </tbody>
                                        </table>
                </div>
<script>
        setTimeout(function(){$("#collapseCompras").addClass("show");},1)
</script>
<div class="modal fade" id="infoCompra" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header" style="background-color:blue;color:white;">
                <h5 class="modal-title" id="exampleModalLongTitle" >Detalles del Registro de Compra</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-bodyCompra">                            
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                
            </div>
            </div>
        </div>
        </div>

        <div class="modal fade" id="delCompra" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header" style="background-color:blue;color:white;">
                <h5 class="modal-title" id="exampleModalLongTitle" >Eliminar Registro de Compra</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-bodyDelCompra">  
            
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                
                <button type="button" class="btn btn-warning" onclick="eliminaCompra()" id="btnEliminarCompra">Eliminar</button>                
            </div>
            </div>
        </div>
        </div>