<!--<script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCaViDOYmj5ZSkqudQmZ0gVFQpS1Ap-SLo&callback=initMap">
</script>
<script>
    class Localizacion{
        constructor(callback){
            if(navigator.geolocation){
                //Obtenemos Ubicación
                navigator.geolocation.getCurrentPosition((position)=>{
                    this.latitude = position.coords.latitude;
                    this.longitude = position.coords.longitude;
                    callback();                    
                });
            }else{
                alert("Tu navegador no soporta Geolocalización :(");
            }
        }
    }    


    function initMap(){
        var ubicacion = new Localizacion(()=>{
            const options = {
                center:{
                    lat:ubicacion.latitude,
                    lng:ubicacion.longitude
                },
                zoom: 18                
            };
            var map = document.getElementById("map");
                const mapa = new google.maps.Map(map,options); 
        });
    }

    var ubicacion = new Localizacion();    
</script>
<style>
    #map{
        width: 500px;
        height: 500px;
    }
</style>
<div id="map">-->
<center>
    <div style="display:table-cell; vertical-align:middle;">
        <hr/>
        <img src="<?php echo $this->path?>/images/logo.png" style="opacity:.2">
        <h3 style="color:gray">Bienvenido <?php echo $this->usuario ?></h3>
    </div>
</center>