<form action="<?php echo $this->path ?>/index/sendpassword" method="POST">
    <center style="">
        <div style=" display:table-cell; vertical-align: middle;height: 300px;background-color:white; padding:20px; border-radius:20px;">
            <h3>Reenvío de Contraseña</h3>
            <p>Indicar el correo electrónico para recuperar la contraseña</p>
            <p><input type="text" name="email" style="width:350px;height:40px;font-size:1.3em;color:black;text-align:center" value="<?php echo isset($this->old) ? $this->old : "" ?>"></input></p>
            <?php if (isset($this->error)) : ?>
                <div class="alert alert-error"><?php echo $this->error ?></div>
            <?php endif; ?>
            <?php if (isset($this->sent)) : ?>
                <div class="alert alert-success"><?php echo $this->sent ?></div>
            <?php endif; ?>
            <p style="text-align: right;">
                <a href="<?php echo $this->path?>/Login"><button type="button" class="btn btn-secondary" style="border-radius:5px;font-size:1.3em">Login</button></a>
                <button type="submit" class="btn btn-primary" style="border-radius:5px;font-size:1.3em">Enviar Contraseña</button>
            </p>
        </div>
    </center>
</form>