
<div class="row">
                            <div class="col-xl-12">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-area mr-1"></i>
                                        Comportamiento de Ventas
                                    </div>
                                    <div id="tempGrafica">
                                    </div>
                                    <div class="card-body"><canvas id="myAreaChart" width="100%" height="20"></canvas></div>
                                </div>
                            </div>
                            
                        </div>
                        <!-- <div class="row">                            
                            <div class="col-xl-6 col-md-9">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Inventarios Bajos</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Ver Detalles</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6 col-md-9">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">Inventarios Óptimos</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Ver Detalles</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>                            
                        </div> -->
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Productos Más Vendidos                                
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr style="background-color:#138496;color:white;">
                                                <th>Id</th>
                                                <th>Nombre</th>
                                                <th>Unidad</th>
                                                <th>Categoria</th>
                                                <th>Existencias</th>
                                                <th>Imagen</th>
                                                <th>Acciones</th>
                                            </tr>
                                        </thead>                                       
                                        <tbody>
                                        <?php if($this->masvendidos!=null):?>
                                        <?php foreach($this->masvendidos as $item):?>
                                            <tr>
                                                <td><?php echo $item->items_id?></td>
                                                <td><?php echo $item->nombre?></td>
                                                <td><?php echo $item->unidad?></td>
                                                <td><?php echo $item->descripcion?></td>
                                                <td><?php echo $item->existencias?></td>
                                                <td style="text-align:center"><img style="width:40px;" src="<?php echo $this->path."/images/items/".$item->avatar?>"></img></td>
                                                <td style="text-align:center"><form action="<?php echo $this->path?>/Productos/editar" method="POST"><input type="hidden" name="items_id" value="<?php echo $item->items_id?>"><button class="btn btn-info"><i class="fa fa-edit"></i></button></form></td>
                                            </tr>                          
                                            <?php endforeach;?>
                                        <?php endif;?>                      
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>