/* Aplicado*/
alter table ventas add column clientes_id int unsigned default 0;

/*nuevo*/
CREATE TABLE IF NOT EXISTS venta_creditos(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ventas_id BIGINT UNSIGNED,
    fecha_abono TIMESTAMP DEFAULT NOW(),
    abono DOUBLE,
    status BOOLEAN DEFAULT 1,
    turnos_id BIGINT UNSIGNED,
    forma VARCHAR(30)
)ENGINE=INNODB;

insert into estrategiaped VALUES
(1,"1.1O1E1","Implementar políticas públicas que brinden acceso a los derechos sociales y promuevan el bienestar económico de la población de escasos ingresos.",1),
(2,"1.1O1E2","Implementar acciones colectivas de mejoramiento territorial y de reconstrucción del tejido social, que involucren a las y los habitantes de las comunidades de Oaxaca para que gocen de una mejor calidad de vida.",1),
(3,"1.2O1E1","Propiciar la seguridad alimentaria para favorecer un estado de nutrición adecuado de los grupos de atención prioritaria.",2),
(4,"1.3O1E1","Propiciar la inclusión social y una mejor calidad de vida de las Personas con Discapacidad de bajos recursos económicos.",3),
(5,"1.3O1E2","Impulsar el goce pleno de los derechos humanos de las personas adultas mayores en situación de vulnerabilidad en Oaxaca.",3),
(6,"1.3O1E3","Incluir en el diseño y ejecución de las políticas públicas la atención integral y respeto de los derechos de la comunidad LGBTTTIQ+.",3),
(7,"1.4O1E1"," Impulsar el fortalecimiento de capacidades de emprendimiento e implementación de proyectos productivos en municipios con vocación migrante.",4),
(8,"1.4O1E2","Establecer módulos de atención integral para migrantes en lugares estratégicos con flujos migratorios altos en el norte de la República Mexicana y Estados Unidos.",4),
(9,"1.5O1E1","Salvaguardar el patrimonio cultural material e inmaterial de Oaxaca, para garantizar su conservación y preservación.",5),
(10,"1.5O1E2","Facilitar el acceso de las personas a los bienes y servicios culturales y fortalecer la participación de la cultura en la economía estatal.",5),
(11,"1.6O1E1","Propiciar la prevención de infecciones de transmisión sexual, adicciones y situaciones que pongan en riesgo el desarrollo integral de las juventudes.",6),
(12,"1.6O1E2","Impulsar mecanismos de formación y capacitación que permitan a las juventudes contar con mejores conocimientos para su inserción en el mundo laboral y su desarrollo económico.",6),
(13,"1.7O1E1","Ampliar la base social físicamente activa e incluyente que contribuya a mejorar la salud y la calidad de vida de la población.",7),
(14,"1.7O1E2","Impulsar el deporte de alto rendimiento en el Estado.",7),
(15,"1.7O1E3","Mejorar la infraestructura deportiva para que la sociedad cuente con espacios idóneos para la práctica de actividad física y/o deportiva.",7),
(16,"1.8O1E1","Incrementar el acceso y la eficiencia terminal de los servicios educativos, reduciendo la deserción y el abandono escolar.",8),
(17,"1.8O1E2","Mejorar la calidad del servicio en todos los niveles educativos.",8),
(18,"1.8O1E3","Incrementar la cobertura de los servicios de Educación en el estado, con pertinencia intercultural e inclusiva, que contribuyan a abatir el rezago en la educación en el Estado.",8),
(19,"1.8O1E4","Promover el servicio educativo en la población vulnerable",8),
(20,"1.8O1E5","Aumentar el desarrollo tecnológico, ciencia y la innovación en el estado de Oaxaca.",8),
(21,"1.9O1E1","Fortalecer la rectoría de los Servicios de Salud en el estado.",9),
(22,"1.9O1E2","Consolidar la operación del Sistema de Salud para el Bienestar.",9),
(23,"1.9O1E3","Fortalecer la atención primaria a la salud.",9),
(24,"2.1O1E1","Vigilar el manejo honesto y transparente de los recursos públicos.",10),
(25,"2.1O1E2","Fortalecer el enfoque de control preventivo en los organismos públicos que, permita evitar actos de corrupción.",10),
(26,"2.2O1E1","Otorgar un servicio eficiente y de calidad a los ciudadanos del estado.",11),
(27,"2.2O1E2","Mantener una comunicación permanente con la ciudadanía.",11),
(28,"2.2O1E3","Impulsar el uso de las Tecnologías de la Información y Comunicación para eficientar los trámites y servicios del Gobierno.",11),
(29,"2.2O1E4","Brindar trámites y servicios eficientes que otorguen certeza jurídica.",11),
(30,"2.3O1E1","Impulsar la planeación estratégica integral en la formulación de instrumentos de planeación.",12),
(31,"2.3O1E2","Consolidar un sistema de información para la planeación.",12),
(32,"2.3O1E3","Impulsar la democracia participativa desde el territorio.",12),
(33,"2.4O1E1","Facilitar el cumplimiento de obligaciones para fortalecer la presencia fiscal en el estado de Oaxaca.",13),
(34,"2.5O1E1","Implementar una gestión del ejercicio del gasto público enfocada en resultados y en la mejora continua.",14),
(35,"2.6O1E1","Consolidar el Sistema de Evaluación del Desempeño de Oaxaca.",15),
(36,"2.6O1E2","Impulsar mecanismos de coordinación interinstitucional para la ejecución y mejora de las políticas públicas.",15),
(37,"3.1O1E1","Fortalecer los servicios de seguridad y protección ciudadana de forma efectiva y profesional.",16),
(38,"3.1O1E2","Fortalecer los factores de protección y prevención de las violencias.",16),
(39,"3.1O1E3","Fortalecer el funcionamiento institucional del sistema penitenciario.",16),
(40,"3.1O1E4","Mejorar la supervisión de las medidas cautelares en el estado.",16),
(41,"3.1O1E5","Promover la atención integral a personas víctimas de delitos del fuero común y de violaciones a derechos humanos cometidos por autoridades estatales y municipales.",16),
(42,"3.2O1E1","Fortalecer los procesos de gestión y atención de demandas.",17),
(43,"3.2O1E2","Impulsar el pleno goce de los derechos humanos de las y los oaxaqueños que habitan y transitan en el territorio oaxaqueño.",17),
(44,"3.3O1E1","Promover la conciliación en los conflictos por tierras entre ejidos o comunidades agrarias.",18),
(45,"3.4O1E1","Impulsar políticas de información y cultura de prevención y protección civil.",19),
(46,"4.1O1E1","Fortalecer la competitividad y la productividad de las ocho regiones, para mejorar las condiciones de vida de la población.",20),
(47,"4.1O1E2","Fortalecer el mercado interno en las ocho regiones del estado, para el abasto, comercio y distribución de productos y servicios existentes en las comunidades.",20),
(48,"4.2O1E1","Fortalecer la oferta exportable y la atracción de inversiones nacionales y extranjeras en las ocho regiones para generar empleos que mejoren la calidad de vida.",21),
(49,"4.2O1E2","Generar mecanismos de mejora regulatoria y de información que favorezcan, protejan y promuevan las actividades económicas bajo prácticas de responsabilidad social.",21),
(50,"4.3O1E1","Asegurar el acceso a la justicia laboral.",22),
(51,"4.3O1E2","Impulsar la generación de empleos dignos y formales en el estado de Oaxaca. ",22),
(52,"4.4O1E1","Impulsar el desarrollo de sitios con potencial turístico.",23),
(53,"4.4O1E2","Mejorar la competitividad de los destinos turísticos consolidados y de las localidades con potencial turístico del estado de Oaxaca.",23),
(54,"4.4O1E3","Promover la oferta turística del estado que permita incrementar la afluencia de visitantes y la derrama económica generada por el turismo en las ocho regiones.",23),
(55,"4.5O1E1","Fomentar la producción, acopio, procesamiento y comercialización de granos básicos, hortalizas, frutales, forrajes, cactáceas, agaves, cultivos agroindustriales y café, en un marco de sostenibilidad para las ocho regiones del estado.  ",24),
(56,"4.5O1E2","Fortalecer la producción y productividad, procesamiento y comercialización de los productos pecuarios del estado.",24),
(57,"4.5O1E3","Promover el aprovechamiento sustentable de los recursos pesqueros y acuícolas en beneficio de los pescadores, acuacultores como productores de alimentos para la población.",24),
(58,"4.6O1E1","Promover la disponibilidad de servicios ambientales en áreas forestales.",25),
(59,"4.6O1E2","Cuidar los recursos naturales para contribuir a la mitigación del cambio climático.",25),
(60,"4.6O1E3","Promover el adecuado manejo silvícola y el valor agregado de la cadena productiva forestal.",25),
(61,"5.1O1E1","Fortalecer las capacidades de planeación del ordenamiento territorial y desarrollo urbano en las localidades y regiones del estado.",26),
(62,"5.1O1E2","Desarrollar acciones de mejora en infraestructura y equipamiento para el desarrollo sostenible de las localidades del estado.",26),
(63,"5.1O1E3","Impulsar proyectos de ampliación de redes de distribución eléctrica y tecnologías alternativas en las comunidades rurales y zonas urbanas de Oaxaca.",26),
(64,"5.1O1E4","Impulsar proyectos de ampliación y mejora de los servicios públicos de telecomunicaciones.",26),
(65,"5.2O1E1","Intervenir caminos rurales a cabeceras, agencias y localidades de los municipios del estado de Oaxaca.",27),
(66,"5.2O1E2","Intervenir carreteras alimentadoras del estado.",27),
(67,"5.3O1E1","Implementar acciones de mejoramiento y construcción de vivienda adecuada para la población vulnerable y marginada.",28),
(68,"5.3O1E2","Implementar mecanismos de acceso al financiamiento para vivienda social.",28),
(69,"5.4O1E1","Promover el acceso de la población al agua con los requerimientos mínimos de potabilidad bajo un esquema de desarrollo incluyente en las localidades del estado.",29),
(70,"5.4O1E2","Promover el acceso de la población a infraestructura de alcantarillado convencional y alternativas viables y adecuadas.",29),
(71,"5.4O1E3","Fortalecer la infraestructura de tratamiento de aguas residuales.",29),
(72,"5.4O1E4","Contribuir a la gestión integrada de los recursos hídricos con especial enfoque a la implementación de soluciones alternativas.",29),
(73,"5.5O1E1","Desarrollar obras de construcción, ampliación, mejoramiento y equipamiento en los planteles educativos públicos de todos los niveles en el estado.",30),
(74,"5.6O1E1","Fortalecer la integridad del patrimonio cultural material oaxaqueño.",31),
(75,"5.7O1E1","Promover vialidades y espacios públicos accesibles y seguros, para las personas que se movilizan a pie, en bicicleta y demás vehículos no motorizados, incentivando estas formas de movilidad activa.",32),
(76,"5.7O1E2","Modernizar el sistema de transporte colectivo urbano, suburbano, metropolitano y foráneo del estado, para que sea incluyente, accesible, eficiente, interconectado, seguro y sostenible.   ",32),
(77,"5.7O1E3","Fortalecer la competitividad del transporte de carga en nuestro estado.",32),
(78,"5.7O1E4","Fortalecer el enfoque sistémico de seguridad vial en el estado.",32),
(79,"T1O1EP1E1","Promover el acceso a la salud y educación inclusiva, equitativa, no sexista y de calidad con énfasis a mujeres indígenas y afromexicanas.",33),
(80,"T1O1EP2E1","Transversalizar la perspectiva de género en las Políticas Públicas de las Instituciones del Poder Ejecutivo Estatal y Municipal.",33),
(81,"T1O1EP2E2","Impulsar la participación de las mujeres en la toma de decisiones, en los distintos niveles de gobierno en igualdad de condiciones que los hombres.",33),
(82,"T1O1EP3E1","Impulsar la perspectiva de género, derechos humanos e interculturalidad en los procesos de acceso a la justicia.",33),
(83,"T1O1EP3E2","Contribuir a prevenir la violencia contra las mujeres, niñas y adolescentes, preservando su dignidad e integridad, con pertinencia cultural.",33),
(84,"T1O1EP4E1","Impulsar la inclusión y empoderamiento de las mujeres en el mercado laboral.",33),
(85,"T1O1EP4E2","Fomentar una cultura de reconocimiento reducción y redistribución de los trabajos domésticos y de cuidados.",33),
(86,"T1O1EP5E1","Impulsar la creación de espacios públicos seguros para las mujeres, niñas, niños y adolescentes, con pertinencia cultural.",33),
(87,"T2O1EP1E1","Fomentar la protección del ambiente y el desarrollo sustentable de la entidad que genere bienestar.",34),
(88,"T2O1EP2E1","Impulsar políticas públicas en materia ambiental para la reducción de emisiones de contaminantes a la atmósfera.",34),
(89,"T2O1EP3E1","Contribuir a garantizar el derecho de toda persona a un ambiente adecuado para su desarrollo y bienestar",34),
(90,"T2O1EP4E1","Impulsar proyectos sostenibles en cuencas y regiones prioritarias de conservación en Oaxaca.",34),
(91,"T2O1EP5E1","Impulsar la generación de espacios públicos e infraestructura social con un enfoque de sostenibilidad.",34),
(92,"T2O1EP5E2","Minimizar los riesgos al entorno ambiental por contaminación de ríos y cuerpos de agua, deforestación y pérdida de la biodiversidad debido a las actividades productivas, servicios y asentamientos humanos.",34),
(93,"T3O1EP1E1","Favorecer la construcción de un Estado de Bienestar con la atención focalizada en los municipios indígenas y afromexicanos con mayor índice de marginación y pobreza de las ocho regiones.",35),
(94,"T3O1EP2E1","Impulsar el servicio de atención con pertinencia cultural en la administración pública estatal.",35),
(95,"T3O1EP3E1","Contribuir a la protección, seguridad y justicia de los pueblos y comunidades indígenas y afromexicanas del estado.",35),
(96,"T3O1EP4E1","Implementar políticas públicas que impulsen el crecimiento y desarrollo económico de los pueblos y comunidades indígenas y afromexicanos del estado.",35),
(97,"T3O1EP5E2","Impulsar el acceso a los servicios básicos, que contribuyan a una mejor calidad de vida de la población indígena y afromexicana.",35),
(98,"T4O1EP1E1","Promover un estado de bienestar para el pleno desarrollo de las niñas, los niños y adolescentes del estado",36),
(99,"T4O1EP2E1","Fortalecer la estructura gubernamental para asegurar la protección integral de los derechos de niñas, niños y adolescentes.  ",36),
(100,"T4O1EP3E1","Promover la protección, seguridad y justicia de las Niñas, Niños y Adolescentes.",36),
(101,"T4O1EP4E1","Proteger contra la explotación económica y el trabajo infantil a los Niños y Niñas y Adolescentes del estado de Oaxaca.",36),
(102,"T4O1EP5E1","Impulsar la generación de espacios públicos e infraestructura social inclusiva para niñas, niños y adolescentes.",36);