<?php switch($this->resultado){?>
<?php case "incorrecta":?>
<div class="alert alert-warning"><i class="fa fa-exclamation-triangle"></i> La contraseña Actual no es Correcta, favor de Intentar nuevamente!</div>
<?php break;?>
<?php case "actualizada":?>
<div class="alert alert-success"><i class="fa fa-check"></i> La contraseña Se ha actualizado Correctamente!</div>
<?php break;?>
<?php case "error":?>
<div class="alert alert-warning"><i class="fa fa-error"></i> Ocurrió un error al actualizar la Contraseña!</div>
<?php break;?>
<?php }?>
