<?php if($this->detalles!=null):?>
<center><h3 style="color:gray;">Cantidades Registradas</h3></center>
            <table class="table table-hover">
                 <thead>
                 <tr>
                    <th>Id</th>
                    <th>Producto</th>
                    <th>Cantidad Registrada</th>
                    <th>Existencias Actuales</th>
                 </tr>  
                 </thead>                       
                 <tbody>
                 <?php foreach($this->detalles as $detalle):?>
                    <tr>
                        <td><?php echo $detalle->items_id?></td>
                        <td><?php echo $detalle->nombre?></td>
                        <td style="text-align:center"><?php echo $detalle->cantidad?></td>
                        <td style="text-align:center"><?php echo $detalle->existencias?></td>
                    </tr>
                 <?php endforeach;?>                
                 </tbody>    
            </table>
<?php else:?>
<div class="alert alert-warning">No existen Detalles de la Compra Registrada!</div>
<?php endif;?>
