<?php if($this->productos!= null):?>
<style>
    .producto:hover{
        background-color: green;
        color: white;
    }
    .zebra{
        background-color: #13849647;
    }
</style>
<table>
<?php $ban=true; foreach($this->productos as $producto): $ban=!$ban;?>    
    <tr class="producto <?php echo $ban?"zebra":""?>" onclick="$('#input_producto').val('<?php echo $producto->clave?>'); $('#lista_producto_v').html(''); $('#lista_productos_v').hide(); addProducto();" style="cursor:pointer">
        <td style="padding:2px;"><?php echo $producto->clave." - ".$producto->nombre;//." - $ ".number_format($producto->precio_publico,2)?></td>
        <td style="padding:2px;"><img style="width:50px;" src="<?php echo $producto->avatar!=""?$this->path."/images/items/".$producto->avatar:""?>"></td>
</tr>
<?php endforeach;?>
</table>
<?php else:?>
    <span style="color:orange;">Artículo no localizado!</span>
<?php endif;?>