<style>
    .sombreado{
        background-color: #F9F7F7;        
    }
</style>
<div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Ventas Realizadas por Comanda Registrada
                            </div>
                            <div class="card-body">
                                <div class="table-responsive" >
                                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0" lang="es" onchange="alert('la tabla cambió')">
                                        <thead>
                                            <tr style="background-color:#0099CA;color:white;">
                                                <th>Id</th>
                                                <th>Fecha</th>
                                                <th>Mesa</th>
                                                <th>Empleado</th>
                                                <th>Estado</th>
                                                <th>Total</th>                                                
                                                <th>Acciones</th>
                                            </tr>
                                        </thead>
                                        <!--<tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Position</th>
                                                <th>Office</th>
                                                <th>Age</th>
                                                <th>Start date</th>
                                                <th>Salary</th>
                                            </tr>
                                        </tfoot>-->
                                        <tbody>  
                                        <?php if($this->mandas!=null): $total=0;?>
                                        <?php foreach($this->mandas  as $manda):?>
                                            <tr>
                                                <td><?php echo $manda->id?></td>
                                                <td style="text-align:center"><?php echo date("d-m-Y",strtotime($manda->fecha_registro))?></td>
                                                <td><?php echo $manda->mesa?></td>
                                                <td><?php echo $manda->empleado?></td>
                                                <td style="text-align:center"><?php echo $manda->estado?></td>
                                                <td style="text-align:right"><?php echo "$ ".number_format($manda->total,2); $sumatoria+=$manda->total;?></td>                                                
                                                <td style="text-align:center"><a href="<?php echo $this->path?>/Mandas/imprimirmanda?mandas_id=<?php echo $manda->id?>" target="_black"><button class="btn btn-success" type="button"><i class="fa fa-print"></i></button></a></td>                                                                                                                             
                                                
                                            </tr>
                                        <?php endforeach;?>
                                        <?php endif;?>                                                                                
                                        </tbody>
                                    </table>
                                </div>
                                <div style="width:95%;text-align:right;font-size:2em;">
                                <hr/>
                                    Total: <span><b><?php echo "$ ".number_format($sumatoria,2);?></b></span>
                                </div>
                            </div>
                        </div>

                        <script>
                            setTimeout(function(){$("#collapseLayouts").addClass("show");},1)
                        </script>