<?php $path = Zend_Layout::getMvcInstance()->getView()->baseUrl(); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="../images/logo_jefatura.png" type="image/ico" />

        <title>Monitoreo de Indicadores Estrategicos del Estado de Oaxaca| </title>

        <!-- Bootstrap -->
        <link href="<?php echo $path ?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo $path ?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo $path ?>/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="<?php echo $path ?>/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

        <!-- bootstrap-progressbar -->
        <link href="<?php echo $path ?>/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="<?php echo $path ?>/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
        <!-- bootstrap-daterangepicker -->
        <link href="<?php echo $path ?>/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

        <!-- Custom Theme Style -->
        <link href="<?php echo $path ?>/build/css/custom.min.css" rel="stylesheet">
    </head>
    <body class="nav-md">


        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="<?php echo $path ?>/Index" class="site_title"><img src="<?php echo $path ?>/images/pin.png" style="width: 30px;"/> <span>SICASAR</span></a>
                        </div>

                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <!--<div class="profile clearfix">
                          <div class="profile_pic">
                            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                          </div>
                        <!--<div class="profile_info">
                          <span>Welcome,</span>
                          <h2>John Doe</h2>
                        </div>
                      </div>-->
                        <!-- /menu profile quick info -->

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <h3>General</h3>
                                <ul class="nav side-menu">
                                    <li style="background-color: transparent"><a><i class="fa fa-asterisk"></i> Mandas <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="text-align: center">
                                            <li><a href="<?php echo $path . "/Index" ?>" style="color:black;"><span style="color: white"><img src="<?php echo $path ?>/images/add.png" style="width: 100px;"/><br/>Agregar</a></li>
                                            <li><a href="<?php echo $path . "/Index" ?>" style="color:black;"><span style="color: white"><img src="<?php echo $path ?>/images/buscar.png" style="width: 40px;"/><br/>Buscar</a></li>
                                            <!--<li><a href="index2.html">Dashboard2</a></li>
                                            <li><a href="index3.html">Dashboard3</a></li-->
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-edit"></i> Productos <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="max-height:300px;overflow: scroll">
                                            
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-desktop"></i> Usuarios <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="max-height:300px;overflow: scroll">
                                            <?php
                                            $modelObjetivo = new Model_ObjetivoPED();
                                            $objetivos = $modelObjetivo->getObjetivos();
                                            if ($objetivos != null) {
                                                foreach ($objetivos as $objetivo):
                                                    switch ($objetivo->idEjePED) {
                                                        case 1:
                                                            $color = "rgb(223,42,113)";
                                                            break;
                                                        case 2:
                                                            $color = "rgb(255,90,36)";
                                                            break;
                                                        case 3:
                                                            $color = "rgb(112,37,116)";
                                                            break;
                                                        case 4:
                                                            $color = "rgb(97,183,57)";
                                                            break;
                                                        case 5:
                                                            $color = "rgb(0,145,128)";
                                                            break;
                                                        case 6:
                                                            $color = "white";
                                                            break;
                                                    }
                                                    ?>

                                                    <li ><a href="#" style="color:<?php echo $color ?>"><?php echo $objetivo->objetivoPEDClave . " " . $objetivo->objetivoPEDDescripcion ?></a></li>
                                                <?php
                                                endforeach;
                                            }
                                            ?> 
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-table"></i> Cocina <span class="fa fa-chevron-down"></span></a>                   
                                        <ul class="nav child_menu" style="max-height:300px;overflow: scroll">
                                            <?php
                                            $modelEstrategiaPED = new Model_EstrategiaPED();
                                            $estrategias = $modelEstrategiaPED->getEstrategias();

                                            if ($estrategias != null) {
                                                foreach ($estrategias as $estrategia):
                                                    switch ($estrategia->idEjePED) {
                                                        case 1:
                                                            $color = "rgb(223,42,113)";
                                                            break;
                                                        case 2:
                                                            $color = "rgb(255,90,36)";
                                                            break;
                                                        case 3:
                                                            $color = "rgb(112,37,116)";
                                                            break;
                                                        case 4:
                                                            $color = "rgb(97,183,57)";
                                                            break;
                                                        case 5:
                                                            $color = "rgb(0,145,128)";
                                                            break;
                                                        case 6:
                                                            $color = "white";
                                                            break;
                                                    }
                                                    ?>

                                                    <li ><a href="#" style="color:<?php echo $color ?>"><?php echo $estrategia->estrategiaPEDClave . " " . $estrategia->estrategiaPEDDescripcion ?></a></li>
                                                <?php
                                                endforeach;
                                            }
                                            ?>                     
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-bar-chart-o"></i>  Barra <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="max-height:300px;overflow: scroll">                                            
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-bar-chart-o"></i>  Caja <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="max-height:300px;overflow: scroll">                                            
                                        </ul>
                                    </li>
                                    <!--<li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                                      <ul class="nav child_menu">
                                        <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                                        <li><a href="fixed_footer.html">Fixed Footer</a></li>
                                      </ul>
                                    </li>
                                  </ul>
                                </div>
                                <div class="menu_section">
                                  <h3>Live On</h3>
                                  <ul class="nav side-menu">
                                    <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                                      <ul class="nav child_menu">
                                        <li><a href="e_commerce.html">E-commerce</a></li>
                                        <li><a href="projects.html">Projects</a></li>
                                        <li><a href="project_detail.html">Project Detail</a></li>
                                        <li><a href="contacts.html">Contacts</a></li>
                                        <li><a href="profile.html">Profile</a></li>
                                      </ul>
                                    </li>
                                    <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                                      <ul class="nav child_menu">
                                        <li><a href="page_403.html">403 Error</a></li>
                                        <li><a href="page_404.html">404 Error</a></li>
                                        <li><a href="page_500.html">500 Error</a></li>
                                        <li><a href="plain_page.html">Plain Page</a></li>
                                        <li><a href="login.html">Login Page</a></li>
                                        <li><a href="pricing_tables.html">Pricing Tables</a></li>
                                      </ul>
                                    </li>
                                    <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                                      <ul class="nav child_menu">
                                          <li><a href="#level1_1">Level One</a>
                                          <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                              <li class="sub_menu"><a href="level2.html">Level Two</a>
                                              </li>
                                              <li><a href="#level2_1">Level Two</a>
                                              </li>
                                              <li><a href="#level2_2">Level Two</a>
                                              </li>
                                            </ul>
                                          </li>
                                          <li><a href="#level1_2">Level One</a>
                                          </li>
                                      </ul>
                                    </li>                  
                                    <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>-->
                                </ul>
                            </div>
                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    </div>
                </div>


                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>

                            <ul class="nav navbar-nav navbar-right">
                                <!--<li class="">
                                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/img.jpg" alt="">John Doe
                                    <span class=" fa fa-angle-down"></span>
                                  </a>
                                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                      <a href="javascript:;">
                                        <span class="badge bg-red pull-right">50%</span>
                                        <span>Settings</span>
                                      </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                  </ul>
                                </li>
                
                                <li role="presentation" class="dropdown">
                                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                  </a>
                                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                    <li>
                                      <a>
                                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                        <span>
                                          <span>John Smith</span>
                                          <span class="time">3 mins ago</span>
                                        </span>
                                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                        </span>
                                      </a>
                                    </li>
                                    <li>
                                      <a>
                                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                        <span>
                                          <span>John Smith</span>
                                          <span class="time">3 mins ago</span>
                                        </span>
                                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                        </span>
                                      </a>
                                    </li>
                                    <li>
                                      <a>
                                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                        <span>
                                          <span>John Smith</span>
                                          <span class="time">3 mins ago</span>
                                        </span>
                                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                        </span>
                                      </a>
                                    </li>
                                    <li>
                                      <a>
                                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                        <span>
                                          <span>John Smith</span>
                                          <span class="time">3 mins ago</span>
                                        </span>
                                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                        </span>
                                      </a>
                                    </li>
                                    <li>
                                      <div class="text-center">
                                        <a>
                                          <strong>See All Alerts</strong>
                                          <i class="fa fa-angle-right"></i>
                                        </a>
                                      </div>
                                    </li>
                                  </ul>
                                </li>-->
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?php echo $this->layout()->content ?>
                </div>



                <!-- /page content -->

                <!-- footer content -->
                <footer>
                    <!-- <div class="pull-right">
                      <a href="https://colorlib.com">Colorlib</a>
                     </div>
                     <div class="clearfix"></div>
                   </footer>-->
                    <!-- /footer content -->
            </div>
        </div>



        <script src="<?php echo $path ?>/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo $path ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="<?php echo $path ?>/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="<?php echo $path ?>/vendors/nprogress/nprogress.js"></script>
        <!-- Chart.js -->
        <script src="<?php echo $path ?>/vendors/Chart.js/dist/Chart.min.js"></script>
        <!-- gauge.js -->
        <script src="<?php echo $path ?>/vendors/gauge.js/dist/gauge.min.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="<?php echo $path ?>/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="<?php echo $path ?>/vendors/iCheck/icheck.min.js"></script>
        <!-- Skycons -->
        <script src="<?php echo $path ?>/vendors/skycons/skycons.js"></script>
        <!-- Flot -->
        <script src="<?php echo $path ?>/vendors/Flot/jquery.flot.js"></script>
        <script src="<?php echo $path ?>/vendors/Flot/jquery.flot.pie.js"></script>
        <script src="<?php echo $path ?>/vendors/Flot/jquery.flot.time.js"></script>
        <script src="<?php echo $path ?>/vendors/Flot/jquery.flot.stack.js"></script>
        <script src="<?php echo $path ?>/vendors/Flot/jquery.flot.resize.js"></script>
        <!-- Flot plugins -->
        <script src="<?php echo $path ?>/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
        <script src="<?php echo $path ?>/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
        <script src="<?php echo $path ?>/vendors/flot.curvedlines/curvedLines.js"></script>
        <!-- DateJS -->
        <script src="<?php echo $path ?>/vendors/DateJS/build/date.js"></script>
        <!-- JQVMap -->
        <script src="<?php echo $path ?>/vendors/jqvmap/dist/jquery.vmap.js"></script>
        <script src="<?php echo $path ?>/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
        <script src="<?php echo $path ?>/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="<?php echo $path ?>/vendors/moment/min/moment.min.js"></script>
        <script src="<?php echo $path ?>/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

        <!-- Custom Theme Scripts -->
        <script src="<?php echo $path ?>/build/js/custom.min.js"></script>    
    </body>
</html>

