<?php $path= Zend_Layout::getMvcInstance()->getView()->baseUrl();?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo $path?>/images/eco.png" type="image/ico" />

    <title>Sistema de Punto de venta Eco + Clean</title>

    <!-- Bootstrap -->
    <link href="<?php echo $path?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $path?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo $path?>/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="<?php echo $path?>/vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo $path?>/build/css/custom.min.css" rel="stylesheet">
    <link href="<?php echo $path?>/build/css/custom.min.css" rel="stylesheet">
    <script src="<?php echo $path?>/vendors/jquery/dist/jquery.min.js"></script>
    
    <script src="<?php echo $path?>/vendors/documentready.js"></script>
    <script src="<?php echo $path?>/vendors/AjaxFunctions.js"></script>
  </head>
  <body class="login" style="background-image: url(<?php echo $path?>/images/fondo.png);background-repeat:no-repeat;height:100% !important; overflow:scroll; margin:0px;">)
  <input type="hidden" id="path" value="<?php echo $path?>">
    <?php echo $this->layout()->content ?>
  </body>
</html>

