<div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <img class="mb-4 img-error" src="../images/error-404-monochrome.svg" />
                                    <p class="lead">Página no encontrada</p>
                                    <a href="<?php echo $this->url?>">
                                        <i class="fas fa-arrow-left mr-1"></i>
                                        Regresar al Inicio
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
